package dev.fizcode.common.util

object AnimeFieldsConstant {
    const val ALTERNATIVE_TITLES = "alternative_titles"
    const val AVERAGE_EPISODE_DURATION = "average_episode_duration"
    const val BACKGROUND = "background"
    const val BROADCAST = "broadcast"
    const val CREATED_AT = "created_at"
    const val END_DATE = "end_date"
    const val GENRES = "genres"
    const val MEAN = "mean"
    const val MEDIA_TYPE = "media_type"
    const val MY_LIST_STATUS = "my_list_status"
    const val NSFW = "nsfw"
    const val NUM_EPISODES = "num_episodes"
    const val NUM_LIST_USERS = "num_list_users"
    const val NUM_SCORING_USERS = "num_scoring_users"
    const val PICTURES = "pictures"
    const val POPULARITY = "popularity"
    const val RANK = "rank"
    const val RATING = "rating"
    const val RECOMMENDATIONS = "recommendations"
    const val RELATED_ANIME = "related_anime"
    const val RELATED_MANGA = "related_manga"
    const val SOURCE = "source"
    const val START_DATE = "start_date"
    const val START_SEASON = "start_season"
    const val STATUS = "status"
    const val STATISTICS = "statistics"
    const val STUDIOS = "studios"
    const val SYNOPSIS = "synopsis"
    const val UPDATED_AT = "updated_at"
}
