package dev.fizcode.common.util

internal object Constant {

    const val COMMA = ","
    const val CURRENTLY_AIRING = "Currently Airing"
    const val EPISODE = "Episode"
    const val EPISODES = "Episodes"
    const val FINISHED_AIRING = "Finished"
    const val HOUR = "hour"
    const val HOURS = "hours"
    const val JST = "JST"
    const val OVA = "OVA"
    const val ONA = "ONA"
    const val MIN = "min."
    const val MINS = "mins."
    const val MOVIE = "Movie"
    const val MUSIC = "Music"
    const val NOT_YET_AIRED = "Not Yet Aired"
    const val SEC = "sec."
    const val SECS = "secs."
    const val SNAKE_CURRENTLY_AIRING = "currently_airing"
    const val SNAKE_FINISHED_AIRING = "finished_airing"
    const val SNAKE_MOVIE = "movie"
    const val SNAKE_MUSIC = "music"
    const val SNAKE_NOT_YET_AIRED = "not_yet_aired"
    const val SNAKE_ONA = "ona"
    const val SNAKE_OVA = "ova"
    const val SNAKE_SPECIAL = "special"
    const val SNAKE_TV = "tv"
    const val SNAKE_TV_SPECIAL = "tv_special"
    const val SPACE = " "
    const val SPECIAL = "Special"
    const val TV = "TV"
    const val TV_SPECIAL = "TV Special"
    const val UNKNOWN_AIRING_TIME = "Unknown Airing Time"
    const val UNKNOWN_AIRING_STATUS = "Unknown Airing Status"
    const val UNKNOWN_MEDIA_TYPE = "Unknown Media Type"
}
