package dev.fizcode.mediadetailinfo.util

internal object Constant {
    const val AIRED = "Aired"
    const val BACKGROUND = "Background"
    const val BROADCAST = "Broadcast"
    const val CHARACTER_IMAGE = "Character Image"
    const val CHARACTERS_AND_VA = "Characters & Voice Actors"
    const val DURATION = "Duration"
    const val ENGLISH = "English"
    const val EXPAND_ICON = "Expand Icon"
    const val EPISODES = "Episodes"
    const val FAVORITES = "Favorites"
    const val GENRES = "Genres"
    const val INFORMATION = "Information"
    const val JAPANESE = "Japanese"
    const val LESS_TITLE = "Less Title"
    const val LICENSORS = "Licensors"
    const val MEMBERS = "Members"
    const val MORE_ICON = "More Icon"
    const val MORE_TITLE = "More Title"
    const val POPULARITY = "Popularity"
    const val PREMIERED = "Premiered"
    const val PRODUCERS = "Producers"
    const val RANKED = "Ranked"
    const val RATING = "Rating"
    const val RELATED = "Related Entries"
    const val SCORE = "Score"
    const val SHARE_ICON = "Share"
    const val SOURCE = "Source"
    const val STAFF = "Staff"
    const val STAFF_IMAGE = "Staff Image"
    const val STATISTICS = "Statistics"
    const val STATUS = "Status"
    const val STUDIOS = "Studios"
    const val SYNONYM = "Synonym"
    const val SYNOPSIS = "Synopsis"
    const val THEMES = "Themes"
    const val TYPE = "Type"
    const val VA_IMAGE = "Voice Actor Image"
}
