name: Fastlane CI

on:
  push:
    branches: [ "release/*/master" ]
  pull_request:
    branches: [ "release/*/master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  devRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "X_MAL_CLIENT_ID=${{ secrets.X_MAL_CLIENT_ID }}" >> local.properties
      - name: Verify local.properties
        run: |
          echo "Contents of local.properties:"
          cat local.properties
      - uses: maierj/fastlane-action@v3.1.0
        with:
          lane: 'devRelease'
      - uses: actions/upload-artifact@v4
        with:
          name: APK
          path: app/build/outputs/apk/**/**/*.apk
